AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 512
Resources:
  AlexaExampleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: "s3://test-alexa-jordangaston/AlexaExample-1.0-test-3.jar"
      Handler: alexaexample.skill.handler.AlexaExampleSkillStreamHandler
      Runtime: java8
      Events:
        AlexaExampleSkillEvent:
          Type: AlexaSkill # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AlexaExampleFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AlexaExampleFunction.Arn
  AlexaExampleFunctionRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AlexaExampleFunctionRole.Arn
